name: mfgtools-nsdrude-emr
version: "git"
base: core18
summary: Freescale/NXP I.MX Chip image deploy tools
description: |
  Freescale/NXP I.MX Chip image deploy tools.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  uuu:
    command: bin/uuu

parts:
  mfgtools:
    plugin: nil
    build-packages: [build-essential, cmake, libusb-1.0-0-dev, make]
    source: https://github.com/NXPmicro/mfgtools.git
    source-commit: a3f490098d2d84f679bf6460214411d31c95bc18
    override-build: |
      cmake . && make -j8
      install -D -t $SNAPCRAFT_PART_INSTALL/bin -m 755 uuu/uuu
    build-packages:
    - libusb-1.0-0-dev
    - libzip-dev
    - libbz2-dev
    - pkg-config
    - cmake
    - libssl-dev
    stage-packages:
    - libusb-1.0-0-dev
